variables:
  IMAGE_HUB: tiangroup/fusionbrain

stages:
  - build
  - deploy

build:
  stage: build
  image: docker:24.0.6
  services:
    - docker:24.0.6-dind
  before_script:
    - docker login -u tiangroup -p $DOCKERHUB_TOKEN
  script:
    - docker pull $IMAGE_HUB:latest || true
    - docker build --cache-from $IMAGE_HUB:latest -f docker/Dockerfile -t $IMAGE_HUB:latest .
    - docker push $IMAGE_HUB:latest
  only:
    - tags

deploy:
  stage: deploy
  image: ubuntu
  before_script:
    - apt-get update -y && apt-get install curl -y
  script:
    - 'curl -H "Authorization: Bearer $WATCHTOWER_HTTP_API_TOKEN" $WATCHTOWER_HOST/v1/update'
  only:
    - tags
