services:
  fusionbrain:
    image: tiangroup/fusionbrain
    restart: unless-stopped
    environment:
      - API_KEY
      - SECRET_KEY
      - IMAGES_HOST
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - backend
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token $CF_TUNNELL_KEY
    networks:
      - backend
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update
    environment:
      - WATCHTOWER_HTTP_API_TOKEN
    labels:
      - com.centurylinklabs.watchtower.enable=false
    networks:
      - backend
networks:
  backend: {}
